<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/13 22:44:09
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
      ),
    ),
  ),
);
