<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tb_ClienteEmpresa', 'doctrine');

/**
 * BaseTb_ClienteEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idallgestempresa
 * @property integer $idempresa
 * @property string $idcliente
 * @property string $correlativo
 * @property string $giro
 * @property string $fono
 * @property string $celular
 * @property string $fax
 * @property string $email
 * @property integer $siclienteweb
 * @property string $claveweb
 * 
 * @method integer           getIdallgestempresa() Returns the current record's "idallgestempresa" value
 * @method integer           getIdempresa()        Returns the current record's "idempresa" value
 * @method string            getIdcliente()        Returns the current record's "idcliente" value
 * @method string            getCorrelativo()      Returns the current record's "correlativo" value
 * @method string            getGiro()             Returns the current record's "giro" value
 * @method string            getFono()             Returns the current record's "fono" value
 * @method string            getCelular()          Returns the current record's "celular" value
 * @method string            getFax()              Returns the current record's "fax" value
 * @method string            getEmail()            Returns the current record's "email" value
 * @method integer           getSiclienteweb()     Returns the current record's "siclienteweb" value
 * @method string            getClaveweb()         Returns the current record's "claveweb" value
 * @method Tb_ClienteEmpresa setIdallgestempresa() Sets the current record's "idallgestempresa" value
 * @method Tb_ClienteEmpresa setIdempresa()        Sets the current record's "idempresa" value
 * @method Tb_ClienteEmpresa setIdcliente()        Sets the current record's "idcliente" value
 * @method Tb_ClienteEmpresa setCorrelativo()      Sets the current record's "correlativo" value
 * @method Tb_ClienteEmpresa setGiro()             Sets the current record's "giro" value
 * @method Tb_ClienteEmpresa setFono()             Sets the current record's "fono" value
 * @method Tb_ClienteEmpresa setCelular()          Sets the current record's "celular" value
 * @method Tb_ClienteEmpresa setFax()              Sets the current record's "fax" value
 * @method Tb_ClienteEmpresa setEmail()            Sets the current record's "email" value
 * @method Tb_ClienteEmpresa setSiclienteweb()     Sets the current record's "siclienteweb" value
 * @method Tb_ClienteEmpresa setClaveweb()         Sets the current record's "claveweb" value
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTb_ClienteEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_ClienteEmpresa');
        $this->hasColumn('idallgestempresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idempresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcliente', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('correlativo', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('giro', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('fono', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('celular', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('fax', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('siclienteweb', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('claveweb', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 15,
             ));

        $this->option('collate', 'SQL_Latin1_General_CP850_CI_AS');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}