<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pedido', 'doctrine');

/**
 * BasePedido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $estado
 * @property string $created_at
 * @property string $updated_at
 * @property Doctrine_Collection $sfGuardUser
 * @property Doctrine_Collection $PedidoTbArticulos
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getUserId()            Returns the current record's "user_id" value
 * @method string              getEstado()            Returns the current record's "estado" value
 * @method string              getCreatedAt()         Returns the current record's "created_at" value
 * @method string              getUpdatedAt()         Returns the current record's "updated_at" value
 * @method Doctrine_Collection getSfGuardUser()       Returns the current record's "sfGuardUser" collection
 * @method Doctrine_Collection getPedidoTbArticulos() Returns the current record's "PedidoTbArticulos" collection
 * @method Pedido              setId()                Sets the current record's "id" value
 * @method Pedido              setUserId()            Sets the current record's "user_id" value
 * @method Pedido              setEstado()            Sets the current record's "estado" value
 * @method Pedido              setCreatedAt()         Sets the current record's "created_at" value
 * @method Pedido              setUpdatedAt()         Sets the current record's "updated_at" value
 * @method Pedido              setSfGuardUser()       Sets the current record's "sfGuardUser" collection
 * @method Pedido              setPedidoTbArticulos() Sets the current record's "PedidoTbArticulos" collection
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePedido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedido');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'string', 19, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 19,
             ));
        $this->hasColumn('updated_at', 'string', 19, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 19,
             ));

        $this->option('collate', 'SQL_Latin1_General_CP850_CI_AS');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser', array(
             'local' => 'pedido_id',
             'foreign' => 'id'));

        $this->hasMany('PedidoTbArticulos', array(
             'local' => 'id',
             'foreign' => 'pedido_id'));
    }
}