<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tb_Articulos', 'doctrine');

/**
 * BaseTb_Articulos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $idallgestempresa
 * @property float $idempresa
 * @property string $idarticulo
 * @property integer $idcategoria
 * @property integer $idaccesorio
 * @property string $nombreweb
 * @property string $textoweb
 * @property string $modelo
 * @property string $marca
 * @property string $imagen
 * @property integer $idgrupoarticulo
 * @property integer $idsubgrupoarticulo
 * @property integer $siactivadoweb
 * @property integer $idestado
 * @property integer $idestadoventas
 * @property float $precioventa
 * 
 * @method float        getIdallgestempresa()   Returns the current record's "idallgestempresa" value
 * @method float        getIdempresa()          Returns the current record's "idempresa" value
 * @method string       getIdarticulo()         Returns the current record's "idarticulo" value
 * @method integer      getIdcategoria()        Returns the current record's "idcategoria" value
 * @method integer      getIdaccesorio()        Returns the current record's "idaccesorio" value
 * @method string       getNombreweb()          Returns the current record's "nombreweb" value
 * @method string       getTextoweb()           Returns the current record's "textoweb" value
 * @method string       getModelo()             Returns the current record's "modelo" value
 * @method string       getMarca()              Returns the current record's "marca" value
 * @method string       getImagen()             Returns the current record's "imagen" value
 * @method integer      getIdgrupoarticulo()    Returns the current record's "idgrupoarticulo" value
 * @method integer      getIdsubgrupoarticulo() Returns the current record's "idsubgrupoarticulo" value
 * @method integer      getSiactivadoweb()      Returns the current record's "siactivadoweb" value
 * @method integer      getIdestado()           Returns the current record's "idestado" value
 * @method integer      getIdestadoventas()     Returns the current record's "idestadoventas" value
 * @method float        getPrecioventa()        Returns the current record's "precioventa" value
 * @method Tb_Articulos setIdallgestempresa()   Sets the current record's "idallgestempresa" value
 * @method Tb_Articulos setIdempresa()          Sets the current record's "idempresa" value
 * @method Tb_Articulos setIdarticulo()         Sets the current record's "idarticulo" value
 * @method Tb_Articulos setIdcategoria()        Sets the current record's "idcategoria" value
 * @method Tb_Articulos setIdaccesorio()        Sets the current record's "idaccesorio" value
 * @method Tb_Articulos setNombreweb()          Sets the current record's "nombreweb" value
 * @method Tb_Articulos setTextoweb()           Sets the current record's "textoweb" value
 * @method Tb_Articulos setModelo()             Sets the current record's "modelo" value
 * @method Tb_Articulos setMarca()              Sets the current record's "marca" value
 * @method Tb_Articulos setImagen()             Sets the current record's "imagen" value
 * @method Tb_Articulos setIdgrupoarticulo()    Sets the current record's "idgrupoarticulo" value
 * @method Tb_Articulos setIdsubgrupoarticulo() Sets the current record's "idsubgrupoarticulo" value
 * @method Tb_Articulos setSiactivadoweb()      Sets the current record's "siactivadoweb" value
 * @method Tb_Articulos setIdestado()           Sets the current record's "idestado" value
 * @method Tb_Articulos setIdestadoventas()     Sets the current record's "idestadoventas" value
 * @method Tb_Articulos setPrecioventa()        Sets the current record's "precioventa" value
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTb_Articulos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_Articulos');
        $this->hasColumn('idallgestempresa', 'float', 12, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'default' => 2,
             'length' => 12,
             ));
        $this->hasColumn('idempresa', 'float', 12, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'default' => 1,
             'length' => 12,
             ));
        $this->hasColumn('idarticulo', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('idcategoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idaccesorio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombreweb', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('textoweb', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('modelo', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('marca', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('imagen', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('idgrupoarticulo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idsubgrupoarticulo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('siactivadoweb', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestadoventas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('precioventa', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));

        $this->option('collate', 'SQL_Latin1_General_CP850_CI_AS');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}