<?php

/**
 * BasePedidoTbArticulos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tb_articulos_id
 * @property integer $pedido_id
 * @property Pedido $Pedido
 * 
 * @method string            getTbArticulosId()   Returns the current record's "tb_articulos_id" value
 * @method integer           getPedidoId()        Returns the current record's "pedido_id" value
 * @method Pedido            getPedido()          Returns the current record's "Pedido" value
 * @method PedidoTbArticulos setTbArticulosId()   Sets the current record's "tb_articulos_id" value
 * @method PedidoTbArticulos setPedidoId()        Sets the current record's "pedido_id" value
 * @method PedidoTbArticulos setPedido()          Sets the current record's "Pedido" value
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePedidoTbArticulos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pedido_tb_articulos');
        $this->hasColumn('tb_articulos_id', 'string', 15, array(
             'type' => 'string',
             'primary' => false,
             'length' => 15,
             ));
        $this->hasColumn('pedido_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => false,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pedido', array(
             'local' => 'pedido_id',
             'foreign' => 'id'));
    }
}