<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tb_CatalogoAccesorios', 'doctrine');

/**
 * BaseTb_CatalogoAccesorios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $idallgestempresa
 * @property float $idempresa
 * @property float $idcategoria
 * @property float $idaccesorio
 * @property string $nombre
 * @property float $siacivadoweb
 * @property string $nombreweb
 * 
 * @method float                 getIdallgestempresa() Returns the current record's "idallgestempresa" value
 * @method float                 getIdempresa()        Returns the current record's "idempresa" value
 * @method float                 getIdcategoria()      Returns the current record's "idcategoria" value
 * @method float                 getIdaccesorio()      Returns the current record's "idaccesorio" value
 * @method string                getNombre()           Returns the current record's "nombre" value
 * @method float                 getSiacivadoweb()     Returns the current record's "siacivadoweb" value
 * @method string                getNombreweb()        Returns the current record's "nombreweb" value
 * @method Tb_CatalogoAccesorios setIdallgestempresa() Sets the current record's "idallgestempresa" value
 * @method Tb_CatalogoAccesorios setIdempresa()        Sets the current record's "idempresa" value
 * @method Tb_CatalogoAccesorios setIdcategoria()      Sets the current record's "idcategoria" value
 * @method Tb_CatalogoAccesorios setIdaccesorio()      Sets the current record's "idaccesorio" value
 * @method Tb_CatalogoAccesorios setNombre()           Sets the current record's "nombre" value
 * @method Tb_CatalogoAccesorios setSiacivadoweb()     Sets the current record's "siacivadoweb" value
 * @method Tb_CatalogoAccesorios setNombreweb()        Sets the current record's "nombreweb" value
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTb_CatalogoAccesorios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_CatalogoAccesorios');
        $this->hasColumn('idallgestempresa', 'float', 12, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('idempresa', 'float', 12, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('idcategoria', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('idaccesorio', 'float', 7, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('siacivadoweb', 'float', 20, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('nombreweb', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 20,
             ));

        $this->option('collate', 'SQL_Latin1_General_CP850_CI_AS');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}