<?php

/**
 * PedidoTbArticulosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoTbArticulosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoTbArticulosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PedidoTbArticulos');
    }
}