<?php

/**
 * Tb_ArticuloCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_ArticuloCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tb_ArticuloCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tb_ArticuloCategoria');
    }
}