<?php

/**
 * Tb_ArticulosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_ArticulosTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object Tb_ArticulosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tb_Articulos');
    }

    public function getAllArticuloMoto($categoria=null, $accesorio=null) {


        if (!$categoria == null && !$accesorio == null) {

            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
                exec sp_WEB_ConsultaArticulosPorGrupo
                @IDAllgestEmpresa=N'2',
                @IDEmpresa=N'1',
                @TextoBuscar=N'',
                @Tipo=N'0',
                @TipoBusqueda=N'0',
                @IDCategoria=N'$categoria',
                @IDAccesorio=N'$accesorio',
                @Letra=N'',
                @RutCliente=N'',
                @PageNum=N'1',
                @MarcaBuscar=N''

                ");
            $this->articulos = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->articulos;
        } 
    }

}