<?php

/**
 * Tb_CatalogoCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Blog
 * @subpackage model
 * @author     Conates
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tb_CatalogoCategoria extends BaseTb_CatalogoCategoria
{
}
