<?php

/**
 * Tb_CatalogoAccesoriosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_CatalogoAccesoriosTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object Tb_CatalogoAccesoriosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tb_CatalogoAccesorios');
    }

    public function getAllCatalogoAccesorio($categoria=null,$accesorio=null) {
        if ($categoria == null && $accesorio == null) {

            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
                EXEC sp_WEB_ConsultaAccesorio @IDAllgestEmpresa = 2, @IDEmpresa = 1, @IDCategoria = null, @IDAccesorio = null
            ");
            $this->categorias = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->categorias;
        } elseif ($categoria != null && $accesorio == null){
            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
                EXEC sp_WEB_ConsultaAccesorio @IDAllgestEmpresa = 2, @IDEmpresa = 1, @IDCategoria = $categoria, @IDAccesorio = null
            ");
            $this->categorias = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->categorias;
        }else{
            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
                EXEC sp_WEB_ConsultaAccesorio @IDAllgestEmpresa = 2, @IDEmpresa = 1, @IDCategoria = $categoria, @IDAccesorio = $accesorio
            ");
            $this->categorias = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->categorias;            
        }
    }

}