<?php

/**
 * Tb_ClienteEmpresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_ClienteEmpresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tb_ClienteEmpresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tb_ClienteEmpresa');
    }
}