<?php

/**
 * Tb_CatalogoCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_CatalogoCategoriaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object Tb_CatalogoCategoriaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tb_CatalogoCategoria');
    }

    public function getAllCatalogoCategoria($id_categoria=null) {

        if ($id_categoria == null) {

            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
           EXEC sp_WEB_ConsultaCategoria @IDAllgestEmpresa = 2, @IDEmpresa = 1, @IDCategoria = null
        ");
            $this->categorias = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->categorias;
        } else {
            $doctrine = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $query = $doctrine->query("
                EXEC sp_WEB_ConsultaCategoria @IDAllgestEmpresa = 2, @IDEmpresa = 1, @IDCategoria = $id_categoria
            ");
            $this->categorias = $query->fetchAll(PDO::FETCH_ASSOC);
            return $this->categorias;
        }
    }

}