<?php

/**
 * Tb_OfertasPorArticuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tb_OfertasPorArticuloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tb_OfertasPorArticuloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tb_OfertasPorArticulo');
    }
}