<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/13 22:32:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=shimano',
  'username' => 'root',
  'password' => 'moscon',
  'name' => 'doctrine',
)),);
